### ISSUE TITLE
error why i try running main.py

### ISSUE THREAD

**Issue by wal-ly** [okuru-xyz/indigo-selfbot#26]
ive ran the setup file and ran the utils file as well (it closes instantly tho) and i have python version 3.10 installed but this error pops up when i try to use the command `python main.py` in cmd

`Traceback (most recent call last):
  File "C:\Users\User\Downloads\indigo-selfbot-main\indigo-selfbot-main\main.py", line 2, in <module>
    from discord.ext import commands
ImportError: cannot import name 'commands' from 'discord.ext' (unknown location)`

**Comment by Shkeffy** [comment]
Do the command 'pip install discord'.

**Comment by Francesco2426** [comment]
make sure you install all of the requirements

**Comment by Gowixx** [comment]
Try uninstalling discord.py and discord.py-self, and then reinstalling discord.py-self
Otherwise, you can set up a Venv
